[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

# 自动启用 Next.js 官方运行时插件，支持动态路由
[[
plugins
]]
  package = "@netlify/plugin-nextjs"

[
build.environment
]
  NEXT_PRIVATE_STANDALONE = "true"